### ISSUE TITLE
App is too wide for iPhone 13 mini

### ISSUE THREAD

**Issue by alfredolito** [lumaa-dev/ThreadedApp#1] opened 2024-07-10 08:12 UTC
**Describe the bug**
The interface is wider than the number of pixels on the phone.

**Expected behavior**
The content/interface to responsively scale to the number of pixels.

**Screenshots**
![IMG_5566](https://github.com/lumaa-dev/ThreadedApp/assets/169030639/cc6110ea-1da4-456c-9dbe-79fc4a11c2dd)

**Information (please complete the following information):**
- iOS Version: iOS 17.5.1
- App Version: Can not find this information. Downloaded from AppStore on July 10, 2024.
- Model: iPhone 13 Mini

**Comment by lumaa-dev** [comment] 2024-07-16 14:12
It seems like I cannot reproduce this problem, can you tell me more about the accessibility features you use? It can be caused by the text sizing accessibility setting.\
![Simulator Screenshot - iPhone 13 mini - 2024-07-16 at 16 11 18](https://github.com/user-attachments/assets/99749f09-2cd5-4116-b02d-e5bac80c8169)

**Comment by alfredolito** [comment] 2024-07-17 17:53
> It seems like I cannot reproduce this problem, can you tell me more about the accessibility features you use? It can be caused by the text sizing accessibility setting.

Nope, that is not turned on.

Screen recording from app and settings: https://www.youtube.com/shorts/pxQQtbHbY5A

**Comment by alfredolito** [comment] 2024-07-22 13:43
Oh found the setting now. ![image](https://github.com/user-attachments/assets/871ba073-0e60-4d0d-9083-5314cb19acd9) in Settings > Display&Brighness > Display Zoom. Setting it to default removes the problem.

**Comment by lumaa-dev** [comment] 2024-07-22 23:29
Ok, I will try to fix this Accessibility issue asap.

**Comment by lumaa-dev** [comment] 2024-07-31 19:26
Hello! Can you try again to see if it's fixed in the new 1.1.0 version? Thank you in advance!

**Closed as not planned** 2024-11-15 22:02 UTC
Labels: bug
